### ISSUE TITLE
Развернуть среду для разработки на хостинге

### ISSUE THREAD

**Issue by LoudNick** [LoudNick/poerty-website#1]
- [x] получить доступ к хостингу
- [x] развернуть nginx (если его там нет)
- [x] развернуть mysql (если нет)
- [x] развернуть wordpress, настроить сайт
- [ ] накатить дамп базы

**Comment by LendLord** [comment]
дамп базы просто так не накатим, сначала надо будет привести к необходимому формату таблиц, данных и т.д.

**Comment by LoudNick** [comment]
@LendLord Мы можем это и руками сделать. Я не думаю что там много таблиц.

**Comment by LendLord** [comment]
в старой скорей всего не много, а в новой может быть и много. Тот же форум структура думаю будет абсолютно другая.

И под руками ты имеешь ввиду, написать скрипт или совсем руками? Просто разносить данные по разным таблицам или объединять в одну может быть очень геморно.

**Comment by LendLord** [comment]
Думаю эту задачу можно закрывать
