### ISSUE TITLE
Перевести плагин для аватаров

### ISSUE THREAD

**Issue by LendLord** [LoudNick/poerty-website#20]
![image](https://cloud.githubusercontent.com/assets/3267031/16212475/8c30001a-3750-11e6-9dd0-fa0d86c46e79.png)
Надо перевести на русский

**Comment by LoudNick** [comment]
![image](https://cloud.githubusercontent.com/assets/2035374/16318418/d2741004-3997-11e6-907e-3dfa1330c6bb.png)

Перевел плагин.
