### ISSUE TITLE
Обновить ссылки в статьях

### ISSUE THREAD

**Issue by LendLord** [LoudNick/poerty-website#21]
В уже перенесенных статьях и постах на форуме могут и наверняка есть ссылки на старый сайт, надо их обновить, что бы вели на аналогичный контент на новом сайте.
http://108.61.211.67/2016/06/19/%D0%A2%D0%B0%D1%82%D1%8C%D1%8F%D0%BD%D0%B0-%D0%A1%D0%B5%D0%BC%D1%91%D0%BD%D0%BE%D0%B2%D0%B0-%D0%B0%D0%B2%D1%82%D0%BE%D1%80-%D0%BF%D1%80%D0%BE%D0%B5%D0%BA%D1%82%D0%B0/

Здесь есть ссылка на старый сайт.

**Comment by Romansev** [comment]
Все форума, на текущих страницах поправил

**Comment by LendLord** [comment]
http://pastebin.com/hf3p9Tte
список ссылок и ид страниц на которых они
все эти ссылки надо обновить

**Comment by LendLord** [comment]
некоторые ссылки ведут на разделы которых у нас нету и не предполагается, их скорей всего имеет смысл как-то выпиливать или оставлять как есть

**Comment by LendLord** [comment]
http://pastebin.com/JgfN1v8i

обновил список ссылок

**Comment by LendLord** [comment]
список уникальных ссылок 
http://pastebin.com/EzBB6aNd

для каждой надо сопоставить аналог с нового сайта и заменить на странице где она встречается.

**Comment by LendLord** [comment]
забираю себе

**Comment by LendLord** [comment]
Обновил все ссылки
