### ISSUE TITLE
Проблема с отступом

### ISSUE THREAD

**Issue by LendLord** [LoudNick/poerty-website#22]
На странице http://108.61.211.67/category/about/ у статьи не правильно выводится отступ
![image](https://cloud.githubusercontent.com/assets/3267031/16234482/3e59be32-37da-11e6-8cb4-a8309dc660c2.png)

**Comment by LoudNick** [comment]
Захардкодил говно, и не жалею.

1. http://108.61.211.67/category/about/
![image](https://cloud.githubusercontent.com/assets/2035374/16320232/6a0bb546-399f-11e6-9420-3b7b1336ee17.png)

2. http://108.61.211.67/2016/06/18/tamerlan-kopyo-sudby/?loggedout=true
![image](https://cloud.githubusercontent.com/assets/2035374/16320246/7d781ea8-399f-11e6-83d6-d8d48bca89ac.png)

3. http://108.61.211.67/category/Novosti/
![image](https://cloud.githubusercontent.com/assets/2035374/16320266/95028cd4-399f-11e6-976d-0ce85b0f4f9a.png)

**Comment by LendLord** [comment]
![image](https://cloud.githubusercontent.com/assets/3267031/16320328/db3105b4-399f-11e6-9076-d6fa13748aef.png)
Надо чутка отступ добавить, думаю сам попробую сделать

**Comment by LendLord** [comment]
![image](https://cloud.githubusercontent.com/assets/3267031/16320472/90962984-39a0-11e6-8c92-7c9461a6f078.png)
Такое точно надо поправить

**Comment by LendLord** [comment]
Все заебись! Никитке чмоки
