### ISSUE TITLE
Попробовать прикрутить логотип фаетон

### ISSUE THREAD

**Issue by LendLord** [LoudNick/poerty-website#23]
Попробовать вырезать со старого сайта логотип фаетон и прикрутить на новый, хз насколько удачно получится, но в ТЗ просит сделать

**Comment by LendLord** [comment]
Повозился в фш, получилось два более менее варианта,хотя оба говно
![image](https://cloud.githubusercontent.com/assets/3267031/16246677/f370e0d2-380e-11e6-9292-bfef96041b2c.png)
![image](https://cloud.githubusercontent.com/assets/3267031/16246713/14ccf108-380f-11e6-8820-c87651c2b2ed.png)


Что выбираем?

**Comment by LendLord** [comment]
еще варианты с тенью
![image](https://cloud.githubusercontent.com/assets/3267031/16246886/dba11f48-380f-11e6-9f2f-2045fb2c0fda.png)

**Comment by LendLord** [comment]
И старый вариант
![image](https://cloud.githubusercontent.com/assets/3267031/16246942/2719d230-3810-11e6-9070-855e5351b182.png)

**Comment by Romansev** [comment]
Последний заебись. Давай его

**Comment by LendLord** [comment]
Какой и был что ли?

**Comment by Romansev** [comment]
Нет, последний из твоих вариантов. Который сейчас стоит в общем

**Comment by LendLord** [comment]
ок, тогда закрываю.
