### ISSUE TITLE
Найти и поставить тему

### ISSUE THREAD

**Issue by LendLord** [LoudNick/poerty-website#4]
Необходимо найти и поставить тему

- http://themeforest.net/category/wordpress

- http://rutracker.org/forum/viewtopic.php?t=5124124

- http://www.elegantthemes.com/

**Comment by Romansev** [comment]
Нихуя похожего нет, самое боле менее близкое по логике, что попадалось 

http://www.elegantthemes.com/demo/?theme=DailyJournal
https://colorlib.com/sparkling/
http://demo.fabthemes.com/bistro/

**Comment by LendLord** [comment]
Варианты и правда так себе...
Ну ладно еще глянем потом
