### ISSUE TITLE
Подготовить сервер на production для переноса сайта

### ISSUE THREAD

**Issue by LoudNick** [LoudNick/poerty-website#43]
- [x] подготовить LAMP + настройки
- [x] подготовить wordpress
- [x] развернуть бекап wordpress с тестового на боевой
- [ ] прикрутить домен faeton

**Comment by LendLord** [comment]
С доменом пока совсем непонятно, надо будет разбираться где его покупали и как перепривязать. Пока эту задачу закрываю, с доменом вопрос отдельно решать будем
